In [1]:
import numpy as np

In [2]:
l = []
for i in range(1,6):
    i = int(input('Enter the number'))
    l.append(i)

print(np.array(l))


Enter the number 21
Enter the number 32
Enter the number 43
Enter the number 54
Enter the number 54


[21 32 43 54 54]


In [3]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [4]:
ar3 = np.array([[[1.0,2,3,4], [12,34,56.6,78], [123,456,789,12]]])
print(ar3)
print(ar3.ndim)
print("Data Type:", ar3.dtype)

[[[  1.    2.    3.    4. ]
  [ 12.   34.   56.6  78. ]
  [123.  456.  789.   12. ]]]
3
Data Type: float64


In [5]:
ar10 = np.array([1,2,3,4], ndmin=10)
print(ar10)
print(ar10.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [6]:
ar_zero = np.zeros(4)
print(ar_zero)

print(ar_zero.ndim)

[0. 0. 0. 0.]
1


In [7]:
ar_zero1 = np.zeros((3,4))
print(ar_zero1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [9]:
ar_one1 = np.ones((3,4))
print(ar_one1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
arr_arrange = np.arange(40)
print(arr_arrange)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [11]:
arr_diagonal = np.eye(3)
print(arr_diagonal)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
ar_lin =  np.linspace(1,10)
print(ar_lin)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [13]:
ar_lin1 = np.linspace(1,10,5)
print(ar_lin1)

[ 1.    3.25  5.5   7.75 10.  ]


In [14]:
random = np.random.rand(5)
print(random)

[0.61243116 0.75281065 0.43903076 0.81427032 0.89270232]


In [15]:
random1 = np.random.rand(2,5)
print(random1)

[[0.10950665 0.46168314 0.33821646 0.82201326 0.12777808]
 [0.62223396 0.58182784 0.09181193 0.49386634 0.86247653]]


In [16]:
randomwith_negative  = np.random.randn(5)
print(randomwith_negative)

[0.2719557  0.4793146  0.93336365 1.51141834 0.04076475]


In [17]:
randomwith_negative1  = np.random.randn(4,5)
print(randomwith_negative1)

[[ 0.08330048 -0.01219719  0.08331467 -1.57012817 -1.57682265]
 [ 1.63332482 -0.88558968 -1.24400347 -1.23427206  1.39561984]
 [ 0.43592297  0.02837547  1.55613966  0.73523517  0.88434976]
 [ 0.79408306 -0.45626112  0.9672063   1.04589872  0.11969302]]


In [21]:
randomwithmin_max_total = np.random.randint(0,100,7)
print(randomwithmin_max_total)

[94 37 44 58 72 60 98]


In [22]:
arr = np.array([1,2,3,4])
arr_add = arr + 1
print(arr_add)

[2 3 4 5]


In [23]:
arr = np.array([1,2,3,4])
arr_add = np.add(arr,10)
print(arr_add)

[11 12 13 14]


In [24]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
arr_add = arr1 + arr2
print(arr_add)

[2 4 6 8]


In [25]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
arr_add = np.add(arr1,arr2)
print(arr_add)

[2 4 6 8]


In [26]:
arr = np.array([1,2,3,4])
arr_add = arr * 10
print(arr_add)

[10 20 30 40]


In [27]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
arr_add = np.multiply(arr1,arr2)
print(arr_add)

[ 1  4  9 16]


In [28]:
arr = np.array([10,20,30,40])
arr_add = arr / 10
print(arr_add)

[1. 2. 3. 4.]


In [29]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
arr_add = np.divide(arr1,arr2)
print(arr_add)

[1. 1. 1. 1.]


In [30]:
arr = np.array([1,2,3,4])
arr_add = arr - 1
print(arr_add)

[0 1 2 3]


In [31]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
arr_add = np.subtract(arr1,arr2)
print(arr_add)

[0 0 0 0]


In [32]:
arr = np.array([10,20,30,40])
arr_add = arr % 3
print(arr_add)

[1 2 0 1]


In [33]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([3,3,3,3])
arr_add = np.mod(arr1,arr2)
print(arr_add)

[1 2 0 1]


In [34]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
arr_add = np.power(arr1,arr2)
print(arr_add)

[  1   4  27 256]


In [35]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
arr_add = np.reciprocal(arr1,arr2)
print(arr_add)

[1 0 0 0]


In [36]:
var = np.array([4,16,49,25,625,144])

print("Minimum No. is:", np.min(var), np.argmin(var))
print("Maximum No. is:", np.max(var), np.argmax(var))
print("Square root is:", np.sqrt(var))

Minimum No. is: 4 0
Maximum No. is: 625 4
Square root is: [ 2.  4.  7.  5. 25. 12.]


In [37]:
var = np.array([[8,7,0],[5,6,7]])
print(np.min(var,axis = 0))

[5 6 0]


In [38]:
var = np.array([[8,7,0],[5,6,7]])
print(np.max(var,axis = 0))

[8 7 7]


In [39]:
var = np.array([[8,7,0],[5,6,7]])
print(np.min(var,axis = 1))

[0 5]


In [40]:
var = np.array([[8,7,0],[5,6,7]])
print(np.max(var,axis = 1))

[8 7]


In [41]:
var = np.array([[2,3],[2,3]])
print(var.shape)

(2, 2)


In [42]:
var = np.array([1,2,3,4,5,5])
x = var.reshape(3,2)
print(x)

[[1 2]
 [3 4]
 [5 5]]


In [43]:
var = np.array([1,2,3,4,5,6,7,8,9])
x = var.reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
var = np.array([1,2,3,4])
print(var[0])

1


In [49]:
var = np.array([[1,2,3],[4,5,6]])
print(var[0,2])

3


In [52]:
var3 = np.array([[[9,8,7,6],[4,5,6,3]]])
for i in var3:
    print(i)

[[9 8 7 6]
 [4 5 6 3]]


In [55]:
var3 = np.array([[[9,8,7,6],[4,5,6,3]]])
for i in var3:
    for j in i:
        print(j)

[9 8 7 6]
[4 5 6 3]


In [56]:
var3 = np.array([[[9,8,7,6],[4,5,6,3]]])
for i in var3:
    for j in i:
        for k in j:
            print(i)

[[9 8 7 6]
 [4 5 6 3]]
[[9 8 7 6]
 [4 5 6 3]]
[[9 8 7 6]
 [4 5 6 3]]
[[9 8 7 6]
 [4 5 6 3]]
[[9 8 7 6]
 [4 5 6 3]]
[[9 8 7 6]
 [4 5 6 3]]
[[9 8 7 6]
 [4 5 6 3]]
[[9 8 7 6]
 [4 5 6 3]]


In [58]:
var3 = np.array([[[9,8,7,6],[4,5,6,3]]])
for i in np.nditer(var3):
    print(i)

9
8
7
6
4
5
6
3


In [60]:
var3 = np.array([[[9,8,7,6],[4,5,6,3]]])
for i,d in np.ndenumerate(var3):
    print(i,d)

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 1, 3) 3


In [62]:
var = np.array([1,2,3,4])
var1 = np.array([1,2,3,4])
merge = np.concatenate((var,var1))
print(merge)

[1 2 3 4 1 2 3 4]


In [64]:
var = np.array([[5,6,7,8],[1,2,3,4]])
var1 = np.array([[7,8,9,0],[1,2,3,4]])
merge = np.concatenate((var,var1))
print(merge)

[[5 6 7 8]
 [1 2 3 4]
 [7 8 9 0]
 [1 2 3 4]]


In [65]:
var = np.array([[5,6,7,8],[1,2,3,4]])
var1 = np.array([[7,8,9,0],[1,2,3,4]])
merge = np.concatenate((var,var1), axis = 1)
print(merge)

[[5 6 7 8 7 8 9 0]
 [1 2 3 4 1 2 3 4]]


In [66]:
var = np.array([[5,6,7,8],[1,2,3,4]])
var1 = np.array([[7,8,9,0],[1,2,3,4]])
merge = np.concatenate((var,var1), axis = 0)
print(merge)

[[5 6 7 8]
 [1 2 3 4]
 [7 8 9 0]
 [1 2 3 4]]


In [76]:
var = np.array([[5,6,7,8],[1,2,3,4]])
var1 = np.array([[7,8,9,0],[1,2,3,4]])
merge = np.stack((var,var1))
merge_row = np.hstack((var,var1))
merge_column = np.vstack((var,var1))
merge_height = np.dstack((var,var1))


print(merge)
print()
print(merge_row)
print()
print(merge_column)
print()
print(merge_height)

[[[5 6 7 8]
  [1 2 3 4]]

 [[7 8 9 0]
  [1 2 3 4]]]

[[5 6 7 8 7 8 9 0]
 [1 2 3 4 1 2 3 4]]

[[5 6 7 8]
 [1 2 3 4]
 [7 8 9 0]
 [1 2 3 4]]

[[[5 7]
  [6 8]
  [7 9]
  [8 0]]

 [[1 1]
  [2 2]
  [3 3]
  [4 4]]]


In [79]:
arr = np.array([1,2,3,4,5,6])
arr_split = np.array_split(arr,6)

print(arr_split)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [81]:
arr = np.array([1,2,3,4,5,2,2,2,3,6])
x  = np.where(arr ==2)
print(x)

(array([1, 5, 6, 7], dtype=int64),)


In [82]:
arr_sort = np.array([43,764,43,0,34,12,2,343,746,8784])
print(np.sort(arr_sort))

[   0    2   12   34   43   43  343  746  764 8784]


In [84]:
var = np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[3 4 5 2 1]


In [87]:
var = np.array([1,2,3,4,5,2,3,4,5,6,7,8,1,2,3,4,5,6,7,7])
x = np.unique(var)
print(x)

[1 2 3 4 5 6 7 8]


In [89]:
var = np.array([1,2,3,4,5,2,3,4,5,6,7,8,1,2,3,4,5,6,7,7])
x = np.unique(var, return_index = True, return_counts = True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 0,  1,  2,  3,  4,  9, 10, 11], dtype=int64), array([2, 3, 3, 3, 3, 2, 3, 1], dtype=int64))


In [90]:
var = np.array([1,2,3,4,5,6])
y = np.resize(var,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


In [99]:
var = np.array([1,2,3,4])

y = np.resize(var, (2,2))
print(y)
print()
print(y.flatten(order = "F"))
print()
print(np.ravel(y))

[[1 2]
 [3 4]]

[1 3 2 4]

[1 2 3 4]


In [100]:
var = np.array([[1,2,3,4],[6,7,8,9]])

y = np.insert(var, 2, 20)
print(y)

[ 1  2 20  3  4  6  7  8  9]


In [101]:
var = np.array([[1,2,3,4],[6,7,8,9]])

y = np.insert(var, [2,3], 20)
print(y)

[ 1  2 20  3 20  4  6  7  8  9]


In [105]:
var = np.array([[1,2,3],[6,7,8]])

y = np.insert(var, 2, 26, axis =1)
print(y)

[[ 1  2 26  3]
 [ 6  7 26  8]]


In [107]:
var = np.array([[1,2,3,4],[6,7,8,4]])

y = np.insert(var, 2, 26, axis =0)
print(y)

[[ 1  2  3  4]
 [ 6  7  8  4]
 [26 26 26 26]]


In [111]:
var = np.array([1,2,3,4])

y = np.append(var, 2)
print(y)

[1 2 3 4 2]


In [113]:
var = np.array([[1,2,3,4],[6,7,8,9]])

y = np.append(var, [[23,45,67,89]], axis = 0)
print(y)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [23 45 67 89]]


In [115]:
var = np.array([[1,2,3,4],[6,7,8,9]])

y = np.delete(var, 2)
print(y)

[1 2 4 6 7 8 9]


In [118]:
var = np.matrix([[1,2,3,4],[6,7,8,9]])
print(var)
print(type(var))

[[1 2 3 4]
 [6 7 8 9]]
<class 'numpy.matrix'>
